# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoSlideMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoSlideMenu
    pod 'SVProgressHUD'
end
